# Generated by Django 5.0.3 on 2024-03-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Empleados',
            new_name='Empleado',
        ),
    ]
